### ISSUE TITLE
problemas para levantar la app

### ISSUE THREAD

**Issue by baltazarAvave** [jaimeferreira11/Pedidos#1]
No logro levantar el proyecto en el emulador
salta este error:
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.herprogramacion.pedidos, PID: 1016
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.herprogramacion.pedidos/com.herprogramacion.pedidos.ui.MainActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                      at android.app.ActivityThread.access$800(ActivityThread.java:135)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5017)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
                      at android.support.v7.app.AppCompatDelegateImplV7.setSupportActionBar(AppCompatDelegateImplV7.java:198)
                      at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:99)
                      at com.herprogramacion.pedidos.ui.MainActivity.onCreate(MainActivity.java:37)
                      at android.app.Activity.performCreate(Activity.java:5231)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5017) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                      at dalvik.system.NativeStart.main(Native Method) 
I/Process: Sending signal. PID: 1016 SIG: 9
Application terminated.

por favor revisar

**Comment by jaimeferreira11** [comment]
Que raro profe, voy a revisar ahora mismo, de todos modos la apk esta
dentro de la carpeta app

https://github.com/jaimeferreira11/Pedidos/tree/master/app

Yo no tuve problemas a la hora de ejecutar en el emulador.

Reviso ahora profe
ᐧ

2016-11-15 13:51 GMT-03:00 Sebastian Martinez <notifications@github.com>:

**Comment by baltazarAvave** [comment]
para que versión de Android esta preparada la apk?

**Comment by jaimeferreira11** [comment]
Api 23. Aqui te mando un pantallazo de el gradle y de la app levantada en
el emulador


ᐧ

2016-11-15 14:03 GMT-03:00 Sebastian Martinez <notifications@github.com>:

**Comment by baltazarAvave** [comment]
ya pude hacer correr en un telefono con version mas reciente de Android,
esta correcto tienen 95. Solo deben mejorar la ultima pantalla, el listado debe ser mas legible

**Comment by jaimeferreira11** [comment]
Gracias profe!
ᐧ

2016-11-15 14:22 GMT-03:00 Sebastian Martinez <notifications@github.com>:
